#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
YOLO-Seg Offline Data Augmentation:
- Supports Mask Augmentation for Instance Segmentation
- Based on Albumentations library
- Input: dataset root (generated by split_dataset.py)
- Output:
  - images/train_aug/  (Original train + Augmented samples)
  - labels/train_aug/
  - data_aug.yaml      (train points to images/train_aug, val remains unchanged)
"""

import argparse
import os
import shutil
import glob
import random
from pathlib import Path
from typing import List, Tuple, Dict, Any
import numpy as np

import cv2
import yaml
import albumentations as A

IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

def load_yaml(p: Path) -> Dict[str, Any]:
    with p.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)

def save_yaml(obj: Dict[str, Any], p: Path) -> None:
    with p.open("w", encoding="utf-8") as f:
        yaml.safe_dump(obj, f, sort_keys=False, allow_unicode=True)

def polygon_to_mask(polygons, img_h, img_w):
    """
    Convert normalized YOLO polygons to binary Mask
    polygon: [x1, y1, x2, y2, ...] normalized coordinates
    """
    mask = np.zeros((img_h, img_w), dtype=np.uint8)
    if not polygons:
        return mask
        
    for poly in polygons:
        poly = np.array(poly).reshape(-1, 2)
        # Denormalize
        poly[:, 0] *= img_w
        poly[:, 1] *= img_h
        pts = poly.astype(np.int32)
        cv2.fillPoly(mask, [pts], 1)
    return mask

def mask_to_polygons(mask):
    """
    Convert binary Mask to normalized YOLO polygons
    """
    h, w = mask.shape
    contours, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    polygons = []
    
    for contour in contours:
        if cv2.contourArea(contour) < 20: # Filter small noise
            continue
        
        poly = contour.flatten().astype(float)
        # Normalize
        poly[0::2] /= w
        poly[1::2] /= h
        poly = np.clip(poly, 0, 1)
        polygons.append(poly.tolist())
        
    return polygons

def read_yolo_seg_label(txt_path: Path, img_h, img_w) -> Tuple[List[int], List[np.ndarray]]:
    """
    Read YOLO-Seg label txt file
    Returns: classes_list, masks_list (binary masks)
    """
    classes = []
    masks = [] # List of single binary masks per object
    
    if not txt_path.exists():
        return classes, masks

    content = txt_path.read_text(encoding="utf-8").strip().splitlines()
    for line in content:
        if not line.strip():
            continue
        parts = line.strip().split()
        if len(parts) < 3: # class x1 y1 ...
            continue
            
        c = int(float(parts[0]))
        coords = list(map(float, parts[1:]))
        
        # Convert single object polygon to mask
        # Note: We generate a mask for each object so albumentations can handle them individually
        mask = polygon_to_mask([coords], img_h, img_w)
        
        classes.append(c)
        masks.append(mask)
        
    return classes, masks

def write_yolo_seg_label(txt_path: Path, classes: List[int], masks: List[np.ndarray]) -> None:
    lines = []
    for c, mask in zip(classes, masks):
        polys = mask_to_polygons(mask)
        for poly in polys:
            # Format: class <x1> <y1> ...
            line = f"{c} " + " ".join([f"{coord:.6f}" for coord in poly])
            lines.append(line)
            
    txt_path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")

def build_transform(
    rotate_deg: float,
    scale_min: float,
    scale_max: float,
    translate: float,
    enable_blur: bool,
    enable_noise: bool
) -> A.Compose:
    
    tfs = [
        # 1. Geometry Transforms
        # Add perspective transform to simulate camera view changes
        A.Perspective(scale=(0.05, 0.1), keep_size=True, p=0.4),
        
        A.ShiftScaleRotate(
            shift_limit=translate,
            scale_limit=(scale_min - 1.0, scale_max - 1.0), 
            rotate_limit=rotate_deg,
            p=0.9, # High probability
            border_mode=cv2.BORDER_CONSTANT,
            value=0,
            mask_value=0 # Fill background with 0
        ),
        
        A.HorizontalFlip(p=0.5),
        
        # 2. Pixel-level Transforms
        A.RandomBrightnessContrast(p=0.4),
        A.HueSaturationValue(p=0.3),
    ]
    
    if enable_blur:
        tfs.append(A.OneOf([
            A.MedianBlur(blur_limit=3, p=0.2),
            A.Blur(blur_limit=3, p=0.2),
            A.ZoomBlur(max_factor=1.05, p=0.3), # Simulate radial blur from fast movement/zoom
        ], p=0.3))
        
    if enable_noise:
        tfs.append(A.GaussNoise(p=0.2))

    # Albumentations with Mask support
    return A.Compose(tfs)

def ensure_empty_dir(p: Path) -> None:
    if p.exists():
        shutil.rmtree(p)
    p.mkdir(parents=True, exist_ok=True)

def main():
    # Calculate default root relative to this script
    project_root = Path(__file__).resolve().parent.parent
    default_root = project_root / "dataset"

    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=str, default=str(default_root), help="Dataset root directory")
    ap.add_argument("--data_yaml", type=str, default="data.yaml", help="Original data.yaml")
    ap.add_argument("--out_yaml", type=str, default="data_aug.yaml", help="Output new yaml")
    
    ap.add_argument("--k_per_image", type=int, default=3, help="Augmentation factor")
    ap.add_argument("--keep_original", action="store_true", default=True, help="Keep original images")
    
    # Augmentation Params
    ap.add_argument("--rotate", type=float, default=15.0)
    # Expand scale range. Lower limit simulates far view (0.25 = 25% size)
    ap.add_argument("--scale_min", type=float, default=0.25)
    ap.add_argument("--scale_max", type=float, default=1.5)
    ap.add_argument("--translate", type=float, default=0.2) # Increase translate for view shift simulation
    ap.add_argument("--enable_blur", action="store_true", default=True)
    ap.add_argument("--seed", type=int, default=42)

    args = ap.parse_args()
    
    random.seed(args.seed)
    np.random.seed(args.seed)
    
    root = Path(args.root).resolve()
    data_yaml_path = root / args.data_yaml
    
    if not data_yaml_path.exists():
        print(f"Error: {data_yaml_path} not found.")
        return

    cfg = load_yaml(data_yaml_path)
    
    # Assume standard directory structure
    train_img_dir = root / "images" / "train"
    train_lbl_dir = root / "labels" / "train"
    
    if not train_img_dir.exists():
        print(f"Error: Train images dir not found at {train_img_dir}")
        return

    # Output Dirs
    out_img_dir = root / "images" / "train_aug"
    out_lbl_dir = root / "labels" / "train_aug"
    ensure_empty_dir(out_img_dir)
    ensure_empty_dir(out_lbl_dir)

    # Transform
    transform = build_transform(
        args.rotate, args.scale_min, args.scale_max, args.translate, 
        args.enable_blur, enable_noise=True
    )

    # Processing
    imgs = sorted([p for p in train_img_dir.rglob("*") if p.suffix.lower() in IMG_EXTS])
    print(f"Found {len(imgs)} training images.")
    
    generated_count = 0
    
    for img_path in imgs:
        lbl_path = train_lbl_dir / (img_path.stem + ".txt")
        
        img = cv2.imread(str(img_path))
        if img is None:
            continue
        h, w = img.shape[:2]
        
        classes, masks = read_yolo_seg_label(lbl_path, h, w)
        
        # 1. Copy Original
        if args.keep_original:
            shutil.copy2(img_path, out_img_dir / f"orig_{img_path.name}")
            if lbl_path.exists():
                shutil.copy2(lbl_path, out_lbl_dir / f"orig_{lbl_path.name}")
            else:
                 # Create empty file to prevent errors
                (out_lbl_dir / f"orig_{lbl_path.name}").touch()

        # 2. Augment
        # Even if masks are empty (background), albumentations works.
        
        for k in range(args.k_per_image):
            if masks:
                aug = transform(image=img, masks=masks)
                aug_img = aug['image']
                aug_masks = aug['masks']
            else:
                aug = transform(image=img)
                aug_img = aug['image']
                aug_masks = []
            
            # Save
            out_stem = f"aug_{img_path.stem}_{k}"
            cv2.imwrite(str(out_img_dir / f"{out_stem}.jpg"), aug_img)
            
            # Convert back to YOLO Seg format
            write_yolo_seg_label(out_lbl_dir / f"{out_stem}.txt", classes, aug_masks)
            generated_count += 1
            
    # Update YAML
    new_cfg = cfg.copy()
    new_cfg['train'] = "images/train_aug" # Update train path
    # Keep val separate
    
    out_yaml = root / args.out_yaml
    save_yaml(new_cfg, out_yaml)
    
    print(f"Data Augmentation Complete.")
    print(f"Total Aug Images Generated: {generated_count}")
    print(f"New YAML saved to: {out_yaml}")
    print(f"Update your train script data param to: {out_yaml}")

if __name__ == "__main__":
    main()
